Connected to base (Python 3.12.4)

In [ ]:
pd.read_sql("""SELECT 
                m.ANHO_MU, 
                m.COD_SIES,
                m.NIV_GLO,
                m.COD_SIES,
                c.FACULTAD
            FROM TABLA_MU_2016_2026 m
            LEFT JOIN CPP_DR2 c
            ON c.SIES=m.COD_SIES""", con_1)

NameError: name 'pd' is not defined

In [ ]:
import pyodbc
import pandas as pd
import numpy as np
from datetime import date

In [ ]:
pd.read_sql("""SELECT 
                m.ANHO_MU, 
                m.COD_SIES,
                m.NIV_GLO,
                m.COD_SIES,
                c.FACULTAD
            FROM TABLA_MU_2016_2026 m
            LEFT JOIN CPP_DR2 c
            ON c.SIES=m.COD_SIES""", con_1)

NameError: name 'con_1' is not defined

In [ ]:
con_1 = pyodbc.connect(
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER=158.170.66.56,{1433};"
    f"DATABASE=PROC01ESTUDIO;"
    f"UID=proceso;"
    f"PWD=Estudio.2024;")

print("Conexión exitosa")

Conexión exitosa

In [ ]:
pd.read_sql("""SELECT 
                m.ANHO_MU, 
                m.COD_SIES,
                m.NIV_GLO,
                m.COD_SIES,
                c.FACULTAD
            FROM TABLA_MU_2016_2026 m
            LEFT JOIN CPP_DR2 c
            ON c.SIES=m.COD_SIES""", con_1)

<ipython-input-5-8d61126298e1>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("""SELECT

,ANHO_MU,COD_SIES,NIV_GLO,COD_SIES,FACULTAD
0,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
1,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
2,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
3,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
4,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
...,...,...,...,...,...
9810399,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None
9810400,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None
9810401,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None
9810402,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None
9810403,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None

In [ ]:
pd.read_sql("""SELECT 
                m.ANHO_MU, 
                m.COD_SIES,
                m.NIV_GLO,
                m.COD_SIES,
                c.FACULTAD
            FROM TABLA_MU_2016_2026 m
            LEFT JOIN CPP_DR2 c
            ON CONCAT(c.SIES, '-', c.ANHO) = CONCAT(m.COD_SIES, '-', m.ANHO_MU)""", con_1)

<ipython-input-6-920076528167>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("""SELECT

,ANHO_MU,COD_SIES,NIV_GLO,COD_SIES,FACULTAD
0,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
1,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
2,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
3,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
4,2025,I71S1C1001J2V1,PREGRADO,I71S1C1001J2V1,Facultad de Administración y Economía
...,...,...,...,...,...
515809,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None
515810,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None
515811,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None
515812,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None
515813,2016,I71S1CN_P_5JNAV5,None,I71S1CN_P_5JNAV5,None

Connected to base (Python 3.12.4)

No kernel connected

Connected to base (Python 3.12.4)

In [ ]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
import numpy as np
from gspread_dataframe import set_with_dataframe

In [ ]:
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name('/home/xenomorfo/Descargas/bamboo-sweep-465617-i4-06b9bd6f36a5.json', scope)
client = gspread.authorize(credentials)

In [ ]:
spreadsheet = client.open_by_key('1r1nsHibT3kCTnSPhiPxOOZU3-pIP5oq5kfLi6pYE')

APIError: APIError: [400]: Request contains an invalid argument.

In [ ]:
spreadsheet = client.open_by_key('1r1nsHibT3kCTnSPhiPxOOZU3-pIP5oq5kfLi6pYE')

APIError: APIError: [400]: Request contains an invalid argument.

In [ ]:
spreadsheet = client.open_by_key('1r1nsHibT3kCTnSPhiPxOOZU3-pIP5oq5kfLi6pYE-os')

In [ ]:
(
gspread.authorize(credentials)
.open_by_key('1r1nsHibT3kCTnSPhiPxOOZU3-pIP5oq5kfLi6pYE-os')
worksheet(rev)
.get_all_values())

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-6-13711f534f94>, line 2)

In [ ]:
(
gspread.authorize(credentials)
.open_by_key('1r1nsHibT3kCTnSPhiPxOOZU3-pIP5oq5kfLi6pYE-os')
.worksheet("rev")
.get_all_values())

[['',
  '',
  '',
  'mat',
  '',
  '',
  'mat_1er_anio',
  '',
  '',
  'jce_doc',
  '',
  '',
  'n°_prog_diurnos',
  '',
  '',
  'tit op',
  '',
  '',
  'ret_1',
  '',
  ''],
 ['DEPARTAMENTOS',
  'Departamentos',
  'Departamentos',
  '2023',
  '2024',
  '2025',
  '2023',
  '2024',
  '2025',
  '2023',
  '2024',
  '2025',
  '2023',
  '2024',
  '2025',
  '2023',
  '2024',
  '2025',
  '2023',
  '2024',
  '2025'],
 ['BACHILLERATO EN CIENCIAS Y HUMANIDADES',
  'Bachillerato En Ciencias Y Humanidades',
  'Bachillerato En Ciencias Y Humanidades',
  '298',
  '234',
  '273',
  '185',
  '127',
  '161',
  '0,68',
  '0,60',
  '0,69',
  '1',
  '1',
  '1',
  'N/A',
  '0,00',
  '0,00',
  '73,5%',
  '0,78',
  '0,78'],
 ['DEPARTAMENTO DE ADMINISTRACION',
  'Departamento De Administracion',
  'Departamento De Administracion',
  '1675',
  '1582',
  '1559',
  '373',
  '340',
  '357',
  '0,25',
  '0,29',
  '0,27',
  '1',
  '1',
  '1',
  '59,3%',
  '0,61',
  '0,62',
  '81,8%',
  '0,84',
  '0,84'],
 ['DEPARTAMENTO DE ECONOMIA',
  'Departamento De Economia',
  'Departamento De Economia',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0,41',
  '0,29',
  '0,30',
  '1',
  '0',
  '0',
  '0,0%',
  '#DIV/0!',
  '#DIV/0!',
  '0,0%',
  '#N/A',
  '#N/A'],
 ['DEPARTAMENTO DE BIOLOGIA',
  'Departamento De Biologia',
  'Departamento De Biologia',
  '270',
  '206',
  '209',
  '48',
  '45',
  '43',
  '0,74',
  '0,42',
  '0,47',
  '1',
  '1',
  '1',
  '13,0%',
  '#DIV/0!',
  '#DIV/0!',
  '68,8%',
  '0,85',
  '0,85'],
 ['DEPARTAMENTO DE CIENCIA Y TECNOLOGIA DE LOS ALIMENTOS',
  'Departamento De Ciencia Y Tecnologia De Los Alimentos',
  'Departamento De Ciencia Y Tecnologia De Los Alimentos',
  '259',
  '170',
  '179',
  '53',
  '35',
  '53',
  '0,58',
  '0,38',
  '0,41',
  '2',
  '2',
  '2',
  '6,5%',
  '0,19',
  '0,14',
  '71,7%',
  '0,77',
  '0,77'],
 ['DEPARTAMENTO DE CONTABILIDAD Y AUDITORIA',
  'Departamento De Contabilidad Y Auditoria',
  'Departamento De Contabilidad Y Auditoria',
  '1048',
  '1125',
  '1131',
  '246',
  '266',
  '250',
  '0,20',
  '0,21',
  '0,32',
  '1',
  '1',
  '1',
  '6,0%',
  '0,50',
  '0,54',
  '92,7%',
  '0,90',
  '0,90'],
 ['DEPARTAMENTO DE EDUCACION',
  'Departamento De Educacion',
  'Departamento De Educacion',
  '188',
  '153',
  '169',
  '46',
  '40',
  '47',
  '0,36',
  '0,25',
  '0,31',
  '1',
  '1',
  '1',
  '55,0%',
  '0,56',
  '0,66',
  '84,8%',
  '0,88',
  '0,88'],
 ['DEPARTAMENTO DE ESTUDIOS POLITICOS',
  'Departamento De Estudios Politicos',
  'Departamento De Estudios Politicos',
  '242',
  '216',
  '208',
  '43',
  '44',
  '46',
  '0,60',
  '0,49',
  '0,64',
  '1',
  '1',
  '1',
  '40,7%',
  '0,55',
  '0,64',
  '93,0%',
  '0,75',
  '0,75'],
 ['DEPARTAMENTO DE FILOSOFIA',
  'Departamento De Filosofia',
  'Departamento De Filosofia',
  '73',
  '67',
  '72',
  '20',
  '17',
  '19',
  '0,91',
  '0,53',
  '0,81',
  '1',
  '1',
  '1',
  '0,0%',
  '0,17',
  '0,23',
  '90,0%',
  '0,75',
  '0,75'],
 ['DEPARTAMENTO DE FISICA',
  'Departamento De Fisica',
  'Departamento De Fisica',
  '545',
  '447',
  '449',
  '116',
  '88',
  '94',
  '0,69',
  '0,29',
  '0,28',
  '3',
  '3',
  '3',
  '4,3%',
  '0,27',
  '0,13',
  '77,6%',
  '0,93',
  '0,93'],
 ['DEPARTAMENTO DE GESTION AGRARIA',
  'Departamento De Gestion Agraria',
  'Departamento De Gestion Agraria',
  '143',
  '105',
  '96',
  '26',
  '20',
  '18',
  '0,25',
  '0,25',
  '0,23',
  '1',
  '1',
  '1',
  '5,1%',
  '0,27',
  '0,20',
  '65,4%',
  '0,90',
  '0,90'],
 ['DEPARTAMENTO DE GESTION Y POLITICAS PUBLICAS',
  'Departamento De Gestion Y Politicas Publicas',
  'Departamento De Gestion Y Politicas Publicas',
  '583',
  '468',
  '435',
  '109',
  '96',
  '125',
  '0,24',
  '0,25',
  '0,35',
  '1',
  '1',
  '1',
  '65,1%',
  '0,67',
  '0,75',
  '76,1%',
  '0,82',
  '0,82'],
 ['DEPARTAMENTO DE HISTORIA',
  'Departamento De Historia',
  'Departamento De Historia',
  '366',
  '321',
  '330',
  '88',
  '71',
  '100',
  '0,55',
  '0,40',
  '0,43',
  '2',
  '2',
  '2',
  '0,0%',
  '0,51',
  '0,55',
  '70,5%',
  '0,69',
  '0,69'],
 ['DEPARTAMENTO DE INGENIERIA ELECTRICA',
  'Departamento De Ingenieria Electrica',
  'Departamento De Ingenieria Electrica',
  '1066',
  '765',
  '731',
  '179',
  '156',
  '157',
  '0,32',
  '0,24',
  '0,42',
  '2',
  '2',
  '2',
  '2,3%',
  '0,24',
  '0,14',
  '62,0%',
  '0,76',
  '0,76'],
 ['DEPARTAMENTO DE INGENIERIA EN MINAS',
  'Departamento De Ingenieria En Minas',
  'Departamento De Ingenieria En Minas',
  '770',
  '556',
  '555',
  '148',
  '125',
  '152',
  '0,35',
  '0,30',
  '0,31',
  '2',
  '2',
  '2',
  '4,2%',
  '0,14',
  '0,05',
  '58,8%',
  '0,69',
  '0,69'],
 ['DEPARTAMENTO DE INGENIERIA EN OBRAS CIVILES',
  'Departamento De Ingenieria En Obras Civiles',
  'Departamento De Ingenieria En Obras Civiles',
  '509',
  '425',
  '419',
  '88',
  '75',
  '101',
  '0,36',
  '0,19',
  '0,21',
  '1',
  '1',
  '1',
  '5,2%',
  '0,40',
  '0,16',
  '78,4%',
  '0,67',
  '0,67'],
 ['DEPARTAMENTO DE INGENIERIA GEOESPACIAL Y AMBIENTAL',
  'Departamento De Ingenieria Geoespacial Y Ambiental',
  'Departamento De Ingenieria Geoespacial Y Ambiental',
  '498',
  '408',
  '385',
  '77',
  '72',
  '110',
  '0,31',
  '0,25',
  '0,15',
  '3',
  '5',
  '6',
  '0,0%',
  '0,10',
  '0,11',
  '64,9%',
  '0,51',
  '0,51'],
 ['DEPARTAMENTO DE INGENIERIA INDUSTRIAL',
  'Departamento De Ingenieria Industrial',
  'Departamento De Ingenieria Industrial',
  '1214',
  '912',
  '875',
  '250',
  '159',
  '181',
  '0,39',
  '0,26',
  '0,21',
  '2',
  '2',
  '2',
  '3,4%',
  '0,34',
  '0,19',
  '75,6%',
  '0,84',
  '0,84'],
 ['DEPARTAMENTO DE INGENIERIA INFORMATICA',
  'Departamento De Ingenieria Informatica',
  'Departamento De Ingenieria Informatica',
  '900',
  '621',
  '653',
  '192',
  '126',
  '159',
  '0,48',
  '0,22',
  '0,26',
  '2',
  '2',
  '2',
  '3,1%',
  '0,21',
  '0,09',
  '84,4%',
  '0,86',
  '0,86'],
 ['DEPARTAMENTO DE INGENIERIA MECANICA',
  'Departamento De Ingenieria Mecanica',
  'Departamento De Ingenieria Mecanica',
  '818',
  '587',
  '571',
  '151',
  '137',
  '173',
  '0,35',
  '0,30',
  '0,28',
  '3',
  '3',
  '3',
  '5,2%',
  '0,18',
  '0,09',
  '58,9%',
  '0,81',
  '0,81'],
 ['DEPARTAMENTO DE INGENIERIA METALURGICA',
  'Departamento De Ingenieria Metalurgica',
  'Departamento De Ingenieria Metalurgica',
  '429',
  '304',
  '280',
  '98',
  '89',
  '89',
  '0,50',
  '0,28',
  '0,31',
  '2',
  '2',
  '2',
  '1,2%',
  '0,03',
  '0,04',
  '50,0%',
  '0,65',
  '0,65'],
 ['DEPARTAMENTO DE INGENIERIA QUIMICA Y BIOPROCESOS',
  'Departamento De Ingenieria Quimica Y Bioprocesos',
  'Departamento De Ingenieria Quimica Y Bioprocesos',
  '763',
  '634',
  '632',
  '151',
  '155',
  '174',
  '0,53',
  '0,37',
  '0,35',
  '3',
  '4',
  '4',
  '2,3%',
  '0,19',
  '0,15',
  '63,6%',
  '0,76',
  '0,76'],
 ['DEPARTAMENTO DE LINGÜISTICA Y LITERATURA',
  'Departamento De Lingüistica Y Literatura',
  'Departamento De Lingüistica Y Literatura',
  '811',
  '638',
  '649',
  '191',
  '126',
  '141',
  '0,16',
  '0,32',
  '0,26',
  '3',
  '3',
  '3',
  '33,1%',
  '0,51',
  '0,49',
  '85,3%',
  '0,92',
  '0,92'],
 ['DEPARTAMENTO DE MATEMATICA Y CIENCIA DE LA COMPUTACION',
  'Departamento De Matematica Y Ciencia De La Computacion',
  'Departamento De Matematica Y Ciencia De La Computacion',
  '822',
  '680',
  '685',
  '140',
  '141',
  '166',
  '0,36',
  '0,18',
  '0,24',
  '4',
  '4',
  '4',
  '7,6%',
  '0,19',
  '0,20',
  '71,4%',
  '0,91',
  '0,91'],
 ['DEPARTAMENTO DE PUBLICIDAD E IMAGEN',
  'Departamento De Publicidad E Imagen',
  'Departamento De Publicidad E Imagen',
  '494',
  '432',
  '433',
  '87',
  '58',
  '97',
  '0,14',
  '0,27',
  '0,26',
  '2',
  '2',
  '3',
  '59,3%',
  '0,62',
  '0,68',
  '90,8%',
  '0,93',
  '0,93'],
 ['DEPARTAMENTO DE QUIMICA DE LOS MATERIALES',
  'Departamento De Quimica De Los Materiales',
  'Departamento De Quimica De Los Materiales',
  '67',
  '246',
  '234',
  '18',
  '58',
  '79',
  '0,85',
  '0,65',
  '0,72',
  '1',
  '3',
  '3',
  '40,0%',
  '0,54',
  '0,35',
  '83,3%',
  '0,71',
  '0,71'],
 ['DEPARTAMENTO DE TECNOLOGIAS DE GESTION',
  'Departamento De Tecnologias De Gestion',
  'Departamento De Tecnologias De Gestion',
  '259',
  '183',
  '266',
  '93',
  '79',
  '122',
  '0,12',
  '0,19',
  '0,13',
  '3',
  '5',
  '5',
  '34,2%',
  '0,41',
  '0,45',
  '78,5%',
  '1,00',
  '1,00'],
 ['DEPARTAMENTO DE TECNOLOGIAS INDUSTRIALES',
  'Departamento De Tecnologias Industriales',
  'Departamento De Tecnologias Industriales',
  '483',
  '233',
  '228',
  '187',
  '80',
  '90',
  '0,19',
  '0,19',
  '0,18',
  '4',
  '4',
  '4',
  '20,7%',
  '0,36',
  '0,27',
  '68,4%',
  '0,68',
  '0,68'],
 ['ESCUELA DE ARQUITECTURA',
  'Escuela De Arquitectura',
  'Escuela De Arquitectura',
  '541',
  '468',
  '478',
  '97',
  '74',
  '100',
  '0,30',
  '0,20',
  '0,18',
  '1',
  '1',
  '1',
  '49,3%',
  '0,74',
  '0,51',
  '90,7%',
  '0,89',
  '0,89'],
 ['ESCUELA DE CIENCIAS DE LA ACTIVIDAD FISICA, EL DEPORTE Y LA SALUD',
  'Escuela De Ciencias De La Actividad Fisica, El Deporte Y La Salud',
  'Escuela De Ciencias De La Actividad Fisica, El Deporte Y La Salud',
  '421',
  '342',
  '386',
  '122',
  '96',
  '108',
  '0,08',
  '0,18',
  '0,20',
  '3',
  '3',
  '3',
  '34,2%',
  '0,51',
  '0,43',
  '79,5%',
  '0,92',
  '0,92'],
 ['ESCUELA DE ENFERMERIA',
  'Escuela De Enfermeria',
  'Escuela De Enfermeria',
  '390',
  '284',
  '248',
  '68',
  '39',
  '41',
  '0,04',
  '0,19',
  '0,19',
  '1',
  '1',
  '1',
  '17,5%',
  '0,52',
  '0,67',
  '85,3%',
  '0,76',
  '0,76'],
 ['ESCUELA DE KINESIOLOGIA',
  'Escuela De Kinesiologia',
  'Escuela De Kinesiologia',
  '290',
  '235',
  '242',
  '52',
  '43',
  '50',
  '0,08',
  '0,23',
  '0,16',
  '1',
  '1',
  '1',
  '23,3%',
  '0,47',
  '0,44',
  '86,5%',
  '0,90',
  '0,90'],
 ['ESCUELA DE MEDICINA',
  'Escuela De Medicina',
  'Escuela De Medicina',
  '591',
  '378',
  '381',
  '93',
  '43',
  '48',
  '0,13',
  '0,09',
  '0,13',
  '1',
  '1',
  '1',
  '74,0%',
  '0,85',
  '0,78',
  '97,8%',
  '0,96',
  '0,96'],
 ['ESCUELA DE OBSTETRICIA Y PUERICULTURA',
  'Escuela De Obstetricia Y Puericultura',
  'Escuela De Obstetricia Y Puericultura',
  '421',
  '306',
  '275',
  '60',
  '41',
  '40',
  '0,07',
  '0,20',
  '0,15',
  '1',
  '1',
  '1',
  '0,0%',
  '0,24',
  '0,29',
  '91,7%',
  '0,92',
  '0,92'],
 ['ESCUELA DE PERIODISMO',
  'Escuela De Periodismo',
  'Escuela De Periodismo',
  '331',
  '301',
  '292',
  '74',
  '60',
  '57',
  '0,22',
  '0,23',
  '0,30',
  '1',
  '1',
  '1',
  '54,4%',
  '0,59',
  '0,63',
  '86,5%',
  '0,82',
  '0,82'],
 ['ESCUELA DE PSICOLOGIA',
  'Escuela De Psicologia',
  'Escuela De Psicologia',
  '595',
  '433',
  '419',
  '126',
  '61',
  '76',
  '0,34',
  '0,33',
  '0,31',
  '1',
  '1',
  '1',
  '47,3%',
  '0,65',
  '0,63',
  '85,7%',
  '0,89',
  '0,89'],
 ['ESCUELA DE TERAPIA OCUPACIONAL',
  'Escuela De Terapia Ocupacional',
  'Escuela De Terapia Ocupacional',
  '275',
  '204',
  '198',
  '52',
  '40',
  '42',
  '0,02',
  '0,01',
  '0,08',
  '1',
  '1',
  '1',
  '78,0%',
  '0,86',
  '0,80',
  '82,7%',
  '0,91',
  '0,91'],
 ['FACULTAD DE DERECHO',
  'Facultad De Derecho',
  'Facultad De Derecho',
  '783',
  '772',
  '897',
  '194',
  '164',
  '201',
  '0,04',
  '0,04',
  '0,15',
  '1',
  '1',
  '1',
  '0,0%',
  '0,03',
  '0,00',
  '78,9%',
  '0,80',
  '0,80'],
 ['FACULTAD DE INGENIERIA',
  'Facultad De Ingenieria',
  'Facultad De Ingenieria',
  '537',
  '552',
  '635',
  '198',
  '180',
  '220',
  '0,00',
  '1,00',
  '1,00',
  '3',
  '3',
  '3',
  'N/A',
  '#DIV/0!',
  '0,09',
  '70,7%',
  '0,45',
  '0,45'],
 ['FACULTAD DE QUIMICA Y BIOLOGIA',
  'Facultad De Quimica Y Biologia',
  'Facultad De Quimica Y Biologia',
  '692',
  '345',
  '342',
  '127',
  '69',
  '71',
  '0,00',
  '1,00',
  '1,00',
  '3',
  '1',
  '1',
  '19,5%',
  '0,38',
  '0,28',
  '82,7%',
  '0,91',
  '0,91'],
 ['FACULTAD DE CIENCIAS MEDICAS',
  'Facultad De Ciencias Medicas',
  'Facultad De Ciencias Medicas',
  'N/A',
  '0',
  '#N/A',
  'N/A',
  '0',
  '#N/A',
  '0,14',
  '0,24',
  '#N/A',
  '8',
  '0',
  '#N/A',
  'N/A',
  '0,41',
  '#N/A',
  'N/A',
  '#N/A',
  '#N/A'],
 ['DEPARTAMENTO DE CIENCIAS DEL AMBIENTE',
  'Departamento De Ciencias Del Ambiente',
  'Departamento De Ciencias Del Ambiente',
  'N/A',
  '0',
  '0',
  'N/A',
  '0',
  '0',
  '0,87',
  '0,54',
  '0,48',
  '1',
  '0',
  '0',
  'N/A',
  '#DIV/0!',
  '#DIV/0!',
  'N/A',
  '#N/A',
  '#N/A'],
 ['Departamento de Matematica y Ciencia de la Computacion',
  'Departamento De Matematica Y Ciencia De La Computacion',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Gestion Agraria',
  'Departamento De Gestion Agraria',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Tecnologias de Gestion',
  'Departamento De Tecnologias De Gestion',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ciencia y Tecnologia de los Alimentos',
  'Departamento De Ciencia Y Tecnologia De Los Alimentos',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Tecnologias Industriales',
  'Departamento De Tecnologias Industriales',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Escuela de Ciencias de la Actividad Fisica, el Deporte y la Salud',
  'Escuela De Ciencias De La Actividad Fisica, El Deporte Y La Salud',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ingenieria Electrica',
  'Departamento De Ingenieria Electrica',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Escuela de Enfermeria',
  'Escuela De Enfermeria',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ingenieria Industrial',
  'Departamento De Ingenieria Industrial',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ingenieria Mecanica',
  'Departamento De Ingenieria Mecanica',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ingenieria en Minas',
  'Departamento De Ingenieria En Minas',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ingenieria Geoespacial y Ambiental',
  'Departamento De Ingenieria Geoespacial Y Ambiental',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ingenieria Informatica',
  'Departamento De Ingenieria Informatica',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Economia',
  'Departamento De Economia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Escuela de Periodismo',
  'Escuela De Periodismo',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ingenieria Quimica y Bioprocesos',
  'Departamento De Ingenieria Quimica Y Bioprocesos',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Estudios Politicos',
  'Departamento De Estudios Politicos',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Quimica de los Materiales',
  'Departamento De Quimica De Los Materiales',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Educacion',
  'Departamento De Educacion',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Historia',
  'Departamento De Historia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Contabilidad y Auditoria',
  'Departamento De Contabilidad Y Auditoria',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ingenieria en Obras Civiles',
  'Departamento De Ingenieria En Obras Civiles',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Ingenieria Metalurgica',
  'Departamento De Ingenieria Metalurgica',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Facultad de Ciencias Medicas',
  'Facultad De Ciencias Medicas',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Administracion',
  'Departamento De Administracion',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Gestion y Politicas Publicas',
  'Departamento De Gestion Y Politicas Publicas',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Fisica',
  'Departamento De Fisica',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Escuela de Arquitectura',
  'Escuela De Arquitectura',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Lingüistica y Literatura',
  'Departamento De Lingüistica Y Literatura',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Facultad de Quimica y Biologia',
  'Facultad De Quimica Y Biologia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Filosofia',
  'Departamento De Filosofia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Bachillerato en Ciencias y Humanidades',
  'Bachillerato En Ciencias Y Humanidades',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Escuela de Kinesiologia',
  'Escuela De Kinesiologia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Escuela de Terapia Ocupacional',
  'Escuela De Terapia Ocupacional',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Facultad de Derecho',
  'Facultad De Derecho',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Departamento de Biologia',
  'Departamento De Biologia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Escuela de Medicina',
  'Escuela De Medicina',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Escuela de Obstetricia y Puericultura',
  'Escuela De Obstetricia Y Puericultura',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['Escuela de Psicologia',
  'Escuela De Psicologia',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],

In [ ]:
rev = (
gspread.authorize(credentials)
.open_by_key('1r1nsHibT3kCTnSPhiPxOOZU3-pIP5oq5kfLi6pYE-os')
.worksheet("rev")
.get_all_values())

In [ ]:
pd.DataFrame(rev[1:], columns=rev[0])

,,,,mat,,,mat_1er_anio,,,jce_doc,...,,n°_prog_diurnos,,,tit op,,,ret_1,,
0,DEPARTAMENTOS,Departamentos,Departamentos,2023,2024,2025,2023,2024,2025,2023,...,2025,2023,2024,2025,2023,2024,2025,2023,2024,2025
1,BACHILLERATO EN CIENCIAS Y HUMANIDADES,Bachillerato En Ciencias Y Humanidades,Bachillerato En Ciencias Y Humanidades,298,234,273,185,127,161,"0,68",...,"0,69",1,1,1,N/A,"0,00","0,00","73,5%","0,78","0,78"
2,DEPARTAMENTO DE ADMINISTRACION,Departamento De Administracion,Departamento De Administracion,1675,1582,1559,373,340,357,"0,25",...,"0,27",1,1,1,"59,3%","0,61","0,62","81,8%","0,84","0,84"
3,DEPARTAMENTO DE ECONOMIA,Departamento De Economia,Departamento De Economia,0,0,0,0,0,0,"0,41",...,"0,30",1,0,0,"0,0%",#DIV/0!,#DIV/0!,"0,0%",#N/A,#N/A
4,DEPARTAMENTO DE BIOLOGIA,Departamento De Biologia,Departamento De Biologia,270,206,209,48,45,43,"0,74",...,"0,47",1,1,1,"13,0%",#DIV/0!,#DIV/0!,"68,8%","0,85","0,85"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Escuela de Psicologia,Escuela De Psicologia,,,,,,,,,...,,,,,,,,,,
82,Departamento de Publicidad e Imagen,Departamento De Publicidad E Imagen,,,,,,,,,...,,,,,,,,,,
83,Facultad de Ingenieria,Facultad De Ingenieria,,,,,,,,,...,,,,,,,,,,
84,Departamento de Ciencias del Ambiente,,,,,,,,,,...,,,,,,,,,,
85,2024,,,,,,,,,,...,,,,,,,,,,

In [ ]:
cidi = (
gspread.authorize(credentials)
.open_by_key('1r1nsHibT3kCTnSPhiPxOOZU3-pIP5oq5kfLi6pYE-os')
.worksheet("cidi")
.get_all_values())



pd.DataFrame(cidi[1:], columns=cidi[0])

,,FACULTAD,AÑO,DEPARTAMENTOS,TOTAL ALUMNOS PREGRADO,ALUMNOS NUEVOS PREGRADO,JCE DR/JCE (i),N° DE CARRERAS DIURNAS,TASA DE TITULACIÓN,TASA DE RETENCIÓN 1ER AÑO,N° DE PROYECTOS ANID,N° PUBLICA WOS Y SCIELO
0,2023-BACHILLERATO EN CIENCIAS Y HUMANIDADES,VICERRECTORIA ACADEMICA,2023,BACHILLERATO EN CIENCIAS Y HUMANIDADES,298,185,"0,68",1,N/A,"73,5%",S/I,S/I
1,2023-DEPARTAMENTO DE ADMINISTRACION,FAE,2023,DEPARTAMENTO DE ADMINISTRACION,1675,373,"0,25",1,"59,3%","81,8%",1,"25,67"
2,2023-DEPARTAMENTO DE ECONOMIA,FAE,2023,DEPARTAMENTO DE ECONOMIA,0,0,"0,41",1,"0,0%","0,0%",5,"4,00"
3,2023-DEPARTAMENTO DE BIOLOGIA,FQYB,2023,DEPARTAMENTO DE BIOLOGIA,270,48,"0,74",1,"13,0%","68,8%",32,"69,67"
4,2023-DEPARTAMENTO DE CIENCIA Y TECNOLOGIA DE L...,FACTEC,2023,DEPARTAMENTO DE CIENCIA Y TECNOLOGIA DE LOS AL...,259,53,"0,58",2,"6,5%","71,7%",17,"35,33"
...,...,...,...,...,...,...,...,...,...,...,...,...
134,,7) Tasa de retención de los maatrículados en e...,,,,,,,,,,
135,,,,,,,,,,,,
136,,,,,,,,,,,,
137,,,,,,,,,,,,
138,,,,2024,Departamento de Economia,0,0,"0,00",#N/A,,,

In [ ]:
cidi = (
gspread.authorize(credentials)
.open_by_key('1r1nsHibT3kCTnSPhiPxOOZU3-pIP5oq5kfLi6pYE-os')
.worksheet("cidi")
.get_all_values())



pd.DataFrame(cidi[1:], columns=cidi[0])

,id,FACULTAD,AÑO,DEPARTAMENTOS,TOTAL ALUMNOS PREGRADO,ALUMNOS NUEVOS PREGRADO,JCE DR/JCE (i),N° DE CARRERAS DIURNAS,TASA DE TITULACIÓN,TASA DE RETENCIÓN 1ER AÑO,N° DE PROYECTOS ANID,N° PUBLICA WOS Y SCIELO
0,2023-BACHILLERATO EN CIENCIAS Y HUMANIDADES,VICERRECTORIA ACADEMICA,2023,BACHILLERATO EN CIENCIAS Y HUMANIDADES,298,185,"0,68",1,N/A,"73,5%",S/I,S/I
1,2023-DEPARTAMENTO DE ADMINISTRACION,FAE,2023,DEPARTAMENTO DE ADMINISTRACION,1675,373,"0,25",1,"59,3%","81,8%",1,"25,67"
2,2023-DEPARTAMENTO DE ECONOMIA,FAE,2023,DEPARTAMENTO DE ECONOMIA,0,0,"0,41",1,"0,0%","0,0%",5,"4,00"
3,2023-DEPARTAMENTO DE BIOLOGIA,FQYB,2023,DEPARTAMENTO DE BIOLOGIA,270,48,"0,74",1,"13,0%","68,8%",32,"69,67"
4,2023-DEPARTAMENTO DE CIENCIA Y TECNOLOGIA DE L...,FACTEC,2023,DEPARTAMENTO DE CIENCIA Y TECNOLOGIA DE LOS AL...,259,53,"0,58",2,"6,5%","71,7%",17,"35,33"
...,...,...,...,...,...,...,...,...,...,...,...,...
134,,7) Tasa de retención de los maatrículados en e...,,,,,,,,,,
135,,,,,,,,,,,,
136,,,,,,,,,,,,
137,,,,,,,,,,,,
138,,,,2024,Departamento de Economia,0,0,"0,00",#N/A,,,